version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=bookpavilion
      - DB_PASSWORD=bookpavilion
      - DB_NAME=bookpavilion
      - GIN_MODE=debug
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    networks:
      - bookpavilion-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=bookpavilion
      - MYSQL_USER=bookpavilion
      - MYSQL_PASSWORD=bookpavilion
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bookpavilion-network
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  mysql-data:

networks:
  bookpavilion-network:
    driver: bridge
